env:
  browser: true
  es2021: true
  node: true
  jest/globals: true
extends: 
  - 'eslint:recommended'
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - jest
rules:
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  import/extensions: 0
